channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - setuptools_scm
  # documentation
  - sphinx>=4.1.1
  - pydata-sphinx-theme
  - sphinx-copybutton
  - myst-parser
  - mistune<2.0 # prevent AttributeError: module 'mistune' has no attribute 'BlockLexer'
  # pip packages
  - pip
  - pip:
    - git+https://github.com/CagtayFabry/sphinx-asdf.git@sphinx-weldx
