name: documentation
on:
  push:
  pull_request:
  # Trigger the workflow on all release created events
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if ./environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/conda_pkgs_dir
            ~/.cache/pip
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('./doc/rtd_environment.yml', './setup.cfg') }}

      - name: Setup Conda Environment
        uses: mamba-org/provision-with-micromamba@v10
        with:
          environment-file: ./doc/rtd_environment.yml
          environment-name: rtd

      - name: activate build env
        shell: bash -l {0}
        run: micromamba activate rtd

#      - name: install dev version again
#        # There is a bug in micromamba, which cd's out of the working-directory during the pip install of weldx.
#        # So the initial env creation lacks weldx, so we install it here.
#        shell: bash -l {0}
#        run: pwd && pip install -e . && pip install git+https://github.com/CagtayFabry/sphinx-asdf.git@sphinx-weldx

      - name: conda info
        shell: bash -l {0}
        run: conda info

      - name: conda list
        shell: bash -l {0}
        run: conda list

      - name: Build docs
        shell: bash -l {0}
        run: sphinx-build -n -b html -d build/doctrees doc build/html --keep-going

      - uses: actions/upload-artifact@v2
        with:
          name: weldx-standard-docs
          path: build/html
